github: Fix release workflow
confidential-containers/td-shim pull request #447
Opened 2022-11-07 07:33 UTC by fidencio

While the release workflow looks for the 'final-pe-boot-kernel.bin' binary, the binary name should actually be 'final-boot-kernel.bin'

Fixes: #446

Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>

2022-11-07 07:34 UTC, fidencio commented
/cc @liuw1

2022-11-07 07:42 UTC, liuw1 requested changes

2022-11-07 07:42 UTC, liuw1 commented on .github/workflows/release.yaml
>          id: upload_release_final_pe_boot_kernel_bin
The id also need to be corrected. 😊

2022-11-07 07:53 UTC, fidencio commented on .github/workflows/release.yaml
>          id: upload_release_final_pe_boot_kernel_bin
Updated, nice catch!

2022-11-07 07:55 UTC, liuw1 approved these changes

2022-11-07 08:31 UTC, fidencio commented
/cc @jyao1

2022-11-08 01:35 UTC, jyao1 approved these changes

2022-11-08 01:35 UTC, merged