Measure payload only when EXTENDMR is not set
confidential-containers/td-shim pull request #618
Opened 2023-11-03 01:05 UTC by gaojiaqi7

Fixes https://github.com/confidential-containers/td-shim/issues/617

2023-11-03 01:42 UTC, jyao1 commented on td-shim-tools/src/metadata.rs
> +                attributes: 3,
why need to change this?

2023-11-06 08:46 UTC, dimakuv requested changes
The PR doesn't work for me. (Maybe I'm doing something wrong?)

Please see https://github.com/confidential-containers/td-shim/issues/617#issuecomment-1794328608

2023-11-06 15:42 UTC, dimakuv approved these changes
The latest changes work fine, thanks!

2023-11-06 16:11 UTC, jyao1 approved these changes

2023-11-08 01:35 UTC, merged